version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        ENVIRONMENT: production
    image: '{{cookiecutter.app_name}}_production:latest'
