version: '3.10'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  {% if cookiecutter.use_celery == 'y' %}rabbitmq_data: {}{% endif %}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: {{cookiecutter.app_name}}_django
    depends_on:
      - postgres
{% if cookiecutter.use_mailhog == 'y' %}      
      - mailhog
{% endif %}
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    ports:
      - "8000:8000"
      - "5678:5678"
    command: /start_local

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: {{cookiecutter.app_name}}_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.local
{% if cookiecutter.use_mailhog == 'y' %}

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
{% endif %}
{% if cookiecutter.use_celery == 'y' %}

  celery:
    image: {{cookiecutter.app_name}}_django
    depends_on:
      - django
      - postgres
      - rabbitmq
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    command: /celery

  celery_schedule:
    image: {{cookiecutter.app_name}}_django
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    command: /celery_schedule

  rabbitmq:
    image: rabbitmq:3.11-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./.envs/.local
{% endif %}
