#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate --noinput
python manage.py compilemessages -l en -l pt_BR
python manage.py collectstatic --noinput 
gunicorn -w 4 -b 0.0.0.0:8000 --access-logfile - {{cookiecutter.app_name}}.wsgi:application
